### ISSUE TITLE
TOC and number_sections in `docx_simple`  does not work

### ISSUE THREAD

**Issue by Edouard-Legoupil** [vidonne/unhcrdown#30]
In  https://vidonne.github.io/unhcrdown/reference/docx_simple.html

I was trying to add the table of content - as explained here: https://ardata-fr.github.io/officeverse/officedown-for-word.html#toc 

by adding 

```
# Table of content

```{r}
block_toc()
```

Ideally it would be great to also have a parameter to number sections like in

```
  word_document: 
    toc: yes
    toc_depth: 2
    number_sections: yes
```
